#!/usr/bin/env bash
# loop that displays "Best School" 10 times and then "Hi"

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
